baseURL: "https://example.com"
languageCode: "en-us"
title: "Norbert Stange Blog"
pygmentsstyle: 'monokai'
enableEmoji: 'true'
googleAnalytics: "UA-92416623-6"
# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors

